#!/usr/bin/env python3
"""Freeing a render from its cream backdrop.

Shared by `make-icon.py` (the chest) and `make-door-art.py` (the map and the
key). All three renders were generated by the author and arrive the same way:
the subject centred on a warm off-white sheet, with a soft grey drop shadow
under it and a small light sparkle in one corner. All of that has to go, so the
artwork can stand on the window, the Dock and the desktop with nothing behind
it.

Needs Pillow (`pip3 install pillow`). The generated files are committed, so
nobody has to run these scripts to build the project.
"""
from PIL import Image, ImageFilter


def cutout(img, bright=110, saturation=0.42):
    """Free the subject by flooding in from the border, keyed on saturation.

    Colour distance cannot do this job: the gold fittings sit *closer* to the
    cream backdrop than the render's own drop shadow does, so any threshold
    that swallows the shadow also eats the fittings. What separates them is
    saturation — the gold is colourful, the backdrop and its shadow are grey.
    So: bright, unsaturated, and connected to the border. All three, or it
    stays.

    The threshold has to clear the anti-aliased rim, where a pixel is part
    subject and part backdrop and lands around 0.33 to 0.37 — well short of
    the gold behind it at 0.55 and up. At 0.32 that rim survived as a pale
    fringe down the chest's right bracket. It cannot be raised much further:
    the chest holds a map whose pale parchment is walled in by a brown edge of
    its own, and somewhere below 0.46 that wall stops holding and the flood
    pours through and eats the map. Measured, not guessed — at 0.42 the chest
    loses the fringe and nothing else, at 0.46 it loses a tenth of itself.

    The flood is what keeps the map safe. Its parchment has pale, washed-out
    patches that are unsaturated enough to look removable on their own, but
    they are walled in by the dark scorched border, so the flood never reaches
    them and they stay. Only background connected to the edge of the frame
    goes — which is also what takes the corner sparkle with it.
    """
    rgb = img.convert("RGB")
    w, h = rgb.size
    px = rgb.load()

    removable = bytearray(w * h)
    for y in range(h):
        row = y * w
        for x in range(w):
            r, g, b = px[x, y]
            mx = r if r > g else g
            if b > mx:
                mx = b
            mn = r if r < g else g
            if b < mn:
                mn = b
            if mx > bright and (mx - mn) / mx < saturation:
                removable[row + x] = 1

    seen = bytearray(w * h)
    stack = []
    for x in range(w):
        for y in (0, h - 1):
            if removable[y * w + x]:
                stack.append((x, y))
    for y in range(h):
        for x in (0, w - 1):
            if removable[y * w + x]:
                stack.append((x, y))

    while stack:
        x, y = stack.pop()
        i = y * w + x
        if seen[i] or not removable[i]:
            continue
        seen[i] = 1
        if x > 0:
            stack.append((x - 1, y))
        if x < w - 1:
            stack.append((x + 1, y))
        if y > 0:
            stack.append((x, y - 1))
        if y < h - 1:
            stack.append((x, y + 1))

    alpha = Image.frombytes("L", (w, h), bytes(0 if v else 255 for v in seen))
    # Tighten by a pixel, then soften: the outermost ring is part backdrop and
    # would glow against a dark tile.
    alpha = alpha.filter(ImageFilter.MinFilter(3)).filter(ImageFilter.GaussianBlur(1.0))
    out = img.convert("RGBA")
    out.putalpha(alpha)
    return out


def unmark(cut, box, offset, bright=110, saturation=0.38):
    """Paint over the render's corner sparkle with clean subject beside it.

    Each of these renders carries a small four-pointed sparkle low on the
    right. On the chest and the key it sat on the backdrop and left with it.
    On the map it fell across the parchment's bottom-right corner — inside the
    silhouette, walled off from the border — so the flood could never reach it
    and it survived as a pale diamond on the scorched edge.

    Finding it is the same test the cut itself uses, bright and unsaturated,
    which separates the grey mark from the brown parchment cleanly. It only
    separates them *here*: run over the whole picture the same numbers also
    match the pale middle of the map, the lit flank of the key and half the
    coins, so `box` holds the search to the corner the mark is actually in.

    Repairing it is a clone, not a blur. `offset` names a patch of the same
    picture to copy from — for the map, the parchment directly above, whose
    tone was measured against the ring around the mark and comes within a
    value or two of it. A statistic taken near the edge cannot do this job:
    every window wide enough to forget the sparkle also reaches past the
    silhouette into the backdrop, and comes back lighter than the burnt edge
    it is supposed to be repairing.

    Alpha is carried through untouched, so the ragged edge is exactly the edge
    the cut produced. Returns the count as well, so a run that finds nothing
    says so rather than passing quietly.
    """
    region = cut.crop(box)
    rgb = region.convert("RGB")
    alpha = region.split()[3]

    mask = Image.new("L", region.size, 0)
    px = rgb.load()
    ap = alpha.load()
    mp = mask.load()
    found = 0
    for y in range(region.height):
        for x in range(region.width):
            if ap[x, y] < 128:
                continue
            r, g, b = px[x, y]
            mx, mn = max(r, g, b), min(r, g, b)
            if mx > bright and (mx - mn) / mx < saturation:
                mp[x, y] = 255
                found += 1

    # Spread past the mark's soft skirt, then feather, so the patch arrives
    # without a rim of its own.
    mask = mask.filter(ImageFilter.MaxFilter(5)).filter(ImageFilter.GaussianBlur(2.0))

    dx, dy = offset
    donor = cut.crop((box[0] + dx, box[1] + dy, box[2] + dx, box[3] + dy)).convert("RGB")
    patched = Image.composite(donor, rgb, mask)
    patched.putalpha(alpha)
    out = cut.copy()
    out.paste(patched, box)
    return out, found


def bbox_of(img):
    return img.split()[3].getbbox()


def fit(img, target, margin):
    """Scale so the subject fills the tile minus a margin, then centre it."""
    box = bbox_of(img)
    sub = img.crop(box)
    w, h = sub.size
    room = target - margin * 2
    k = min(room / w, room / h)
    sub = sub.resize((max(1, int(w * k)), max(1, int(h * k))), Image.LANCZOS)
    out = Image.new("RGBA", (target, target), (0, 0, 0, 0))
    out.paste(sub, ((target - sub.width) // 2, (target - sub.height) // 2), sub)
    return out
