#!/usr/bin/env python3
"""Builds the app icon from the chest render in `assets/chest-source.png`.

    python3 scripts/make-icon.py

Writes `assets/AppIcon.icns` for the macOS bundle and `src/icon_data.rs` for
the window icon, which is embedded rather than loaded from the bundle: the icon
cache once held on to a placeholder after a bad build, and a binary that
carries its own icon cannot be caught out that way.

The source render was generated by the author and sits on a cream backdrop,
which fought with the dark interface. It is cut out here and set on the same
tile the program uses, so the icon and the window belong to each other.

Needs Pillow (`pip3 install pillow`). The generated files are committed, so
nobody has to run this to build the project.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFilter


N = 1024

BG_TOP = (32, 36, 48)
BG_BOT = (11, 13, 19)
BORDER = (54, 62, 84)
GLOW = (255, 205, 132)


def ramp(top, bottom, size):
    strip = Image.new("RGB", (1, 256))
    for y in range(256):
        f = y / 255
        strip.putpixel((0, y), tuple(int(top[i] + (bottom[i] - top[i]) * f) for i in range(3)))
    return strip.resize((size, size)).convert("RGBA")


def round_mask(size, inset, radius):
    m = Image.new("L", (size, size), 0)
    ImageDraw.Draw(m).rounded_rectangle([inset, inset, size - inset, size - inset], radius, fill=255)
    return m


def cutout(img):
    """Free the chest by flooding in from the border, keyed on saturation.

    Colour distance cannot do this job: the gold fittings sit *closer* to the
    cream backdrop than the render's own drop shadow does, so any threshold
    that swallows the shadow also eats the fittings. What separates them is
    saturation — the gold is colourful, the backdrop and its shadow are grey.
    So: bright, unsaturated, and connected to the border. All three, or it
    stays.
    """
    rgb = img.convert("RGB")
    w, h = rgb.size
    px = rgb.load()

    removable = bytearray(w * h)
    for y in range(h):
        row = y * w
        for x in range(w):
            r, g, b = px[x, y]
            mx = r if r > g else g
            if b > mx:
                mx = b
            mn = r if r < g else g
            if b < mn:
                mn = b
            if mx > 110 and (mx - mn) / mx < 0.32:
                removable[row + x] = 1

    seen = bytearray(w * h)
    stack = []
    for x in range(w):
        for y in (0, h - 1):
            if removable[y * w + x]:
                stack.append((x, y))
    for y in range(h):
        for x in (0, w - 1):
            if removable[y * w + x]:
                stack.append((x, y))

    while stack:
        x, y = stack.pop()
        i = y * w + x
        if seen[i] or not removable[i]:
            continue
        seen[i] = 1
        if x > 0:
            stack.append((x - 1, y))
        if x < w - 1:
            stack.append((x + 1, y))
        if y > 0:
            stack.append((x, y - 1))
        if y < h - 1:
            stack.append((x, y + 1))

    alpha = Image.frombytes("L", (w, h), bytes(0 if v else 255 for v in seen))
    # Tighten by a pixel, then soften: the outermost ring is part backdrop and
    # would glow against a dark tile.
    alpha = alpha.filter(ImageFilter.MinFilter(3)).filter(ImageFilter.GaussianBlur(1.0))
    out = img.convert("RGBA")
    out.putalpha(alpha)
    return out


def bbox_of(img):
    return img.split()[3].getbbox()


def fit(img, target, margin):
    """Scale so the subject fills the tile minus a margin, then centre it."""
    box = bbox_of(img)
    sub = img.crop(box)
    w, h = sub.size
    room = target - margin * 2
    k = min(room / w, room / h)
    sub = sub.resize((max(1, int(w * k)), max(1, int(h * k))), Image.LANCZOS)
    out = Image.new("RGBA", (target, target), (0, 0, 0, 0))
    out.paste(sub, ((target - sub.width) // 2, (target - sub.height) // 2), sub)
    return out


def light_tile(src):
    img = src.convert("RGB").resize((N, N), Image.LANCZOS)
    out = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    out.paste(img.convert("RGBA"), (0, 0), round_mask(N, 22, 228))
    ring = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    ImageDraw.Draw(ring).rounded_rectangle(
        [22, 22, N - 22, N - 22], 228, outline=(198, 184, 166, 255), width=3
    )
    return Image.alpha_composite(out, ring)


def dark_tile(cut):
    base = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    base.paste(ramp(BG_TOP, BG_BOT, N), (0, 0), round_mask(N, 22, 228))

    glow = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    for r, a in ((420, 18), (300, 26), (200, 34), (120, 44)):
        gd.ellipse([N // 2 - r, 470 - r * 0.7, N // 2 + r, 470 + r * 0.7], fill=GLOW + (a,))
    base = Image.alpha_composite(base, glow.filter(ImageFilter.GaussianBlur(60)))

    subject = fit(cut, N, 96)

    shadow = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    sd = ImageDraw.Draw(shadow)
    b = bbox_of(subject)
    cx = (b[0] + b[2]) // 2
    half = int((b[2] - b[0]) * 0.42)
    sd.ellipse([cx - half, b[3] - 30, cx + half, b[3] + 34], fill=(0, 0, 0, 195))
    base = Image.alpha_composite(base, shadow.filter(ImageFilter.GaussianBlur(30)))

    out = Image.alpha_composite(base, subject)
    clipped = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    clipped.paste(out, (0, 0), round_mask(N, 22, 228))
    ring = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    ImageDraw.Draw(ring).rounded_rectangle(
        [22, 22, N - 22, N - 22], 228, outline=BORDER + (255,), width=3
    )
    return Image.alpha_composite(clipped, ring)



def render():
    here = os.path.dirname(os.path.abspath(__file__))
    source = os.path.join(os.path.dirname(here), "assets", "chest-source.png")
    return dark_tile(cutout(Image.open(source)))


ICONSET_SIZES = [16, 32, 64, 128, 256, 512, 1024]

RS_HEADER = """//! The application icon as raw RGBA, generated from the same artwork as
//! `AppIcon.icns`.
//!
//! Carried inside the binary and handed to the window system at startup, so the
//! icon does not depend on macOS resolving the bundle resource — which it
//! failed to do once already, after the bundle had briefly shipped a shell
//! script as its executable and the icon cache remembered a placeholder.
//!
//! Generated by `scripts/make-icon.py`; edit the artwork there, not here.

pub const ICON_W: u32 = {n};
pub const ICON_H: u32 = {n};

#[rustfmt::skip]
pub static ICON_RGBA: [u8; {total}] = [
"""


def write_rust(master, path, n=128):
    small = master.resize((n, n), Image.LANCZOS)
    data = list(small.tobytes())
    out = [RS_HEADER.format(n=n, total=len(data))]
    for i in range(0, len(data), 24):
        out.append("    " + ", ".join(str(b) for b in data[i : i + 24]) + ",\n")
    out.append("];\n")
    with open(path, "w") as f:
        f.write("".join(out))


def write_icns(master, path):
    import shutil
    import subprocess
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        iconset = os.path.join(tmp, "AppIcon.iconset")
        os.makedirs(iconset)
        for size in ICONSET_SIZES:
            img = master.resize((size, size), Image.LANCZOS)
            img.save(os.path.join(iconset, f"icon_{size}x{size}.png"))
            # The @2x variants are what Retina actually draws.
            if size >= 32:
                img.save(os.path.join(iconset, f"icon_{size // 2}x{size // 2}@2x.png"))
        subprocess.run(
            ["iconutil", "-c", "icns", iconset, "-o", os.path.join(tmp, "AppIcon.icns")],
            check=True,
        )
        shutil.copy(os.path.join(tmp, "AppIcon.icns"), path)


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    master = render()

    if len(sys.argv) > 1:
        master.save(sys.argv[1])
        sys.exit(0)

    write_rust(master, os.path.join(root, "src", "icon_data.rs"))
    print("wrote src/icon_data.rs", file=sys.stderr)
    write_icns(master, os.path.join(root, "assets", "AppIcon.icns"))
    print("wrote assets/AppIcon.icns", file=sys.stderr)
