#!/usr/bin/env python3
"""Builds the app icon from the chest render in `assets/chest-source.png`.

    python3 scripts/make-icon.py

Writes `assets/AppIcon.icns` for the macOS bundle and `src/icon_data.rs` for
the window icon, which is embedded rather than loaded from the bundle: the icon
cache once held on to a placeholder after a bad build, and a binary that
carries its own icon cannot be caught out that way.

The source render was generated by the author and sits on a cream backdrop.
It is cut out here — by `cutout.py`, which the door artwork shares — and left
standing on nothing at all: the icon is the chest, with no plate behind it, on
the desktop and in the Dock as well as inside the window. macOS would normally
expect a rounded square, and this deliberately is not one.

Needs Pillow (`pip3 install pillow`). The generated files are committed, so
nobody has to run this to build the project.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFilter

from cutout import cutout, fit


N = 1024

GLOW = (255, 205, 132)


def free_mark(cut):
    """The chest, standing on nothing.

    There used to be a tile behind it — a dark rounded square with a gradient,
    a border and a drop shadow — because that is the shape macOS expects of an
    icon. It was wrong in both places it appeared. Inside the window its
    gradient starts at (32, 36, 48) where the window paints (13, 15, 22), so it
    read as a lighter box around the chest with a visible seam. On the desktop
    it was a black slab behind an object that looks better without one.

    The warm glow stays. It is a soft radial that reads as light coming off the
    gold rather than as an edge, and it keeps the chest from looking pasted on.
    The drop shadow does not: an opaque ellipse with nothing to fall on is just
    a grey smudge.
    """
    out = Image.new("RGBA", (N, N), (0, 0, 0, 0))

    glow = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    for r, a in ((420, 14), (300, 20), (200, 26), (120, 34)):
        gd.ellipse([N // 2 - r, 470 - r * 0.7, N // 2 + r, 470 + r * 0.7], fill=GLOW + (a,))
    out = Image.alpha_composite(out, glow.filter(ImageFilter.GaussianBlur(60)))

    # With no plate to sit inside, the chest may use nearly the whole square.
    return Image.alpha_composite(out, fit(cut, N, 40))


def render():
    here = os.path.dirname(os.path.abspath(__file__))
    source = os.path.join(os.path.dirname(here), "assets", "chest-source.png")
    return free_mark(cutout(Image.open(source)))


ICONSET_SIZES = [16, 32, 64, 128, 256, 512, 1024]

def write_png(master, path, n=512):
    """The window icon, as a PNG the binary carries and decodes at startup.

    It used to be a raw RGBA array in the source. At 128 pixels that array was
    already 2700 lines, and the intro screen draws the mark at 420 physical
    pixels on a Retina display, so it arrived visibly soft. Storing the same
    thing at 512 as an array would be a megabyte of Rust source; as a PNG it is
    a fraction of that and sharp.
    """
    master.resize((n, n), Image.LANCZOS).save(path)


def write_icns(master, path):
    import shutil
    import subprocess
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        iconset = os.path.join(tmp, "AppIcon.iconset")
        os.makedirs(iconset)
        for size in ICONSET_SIZES:
            img = master.resize((size, size), Image.LANCZOS)
            img.save(os.path.join(iconset, f"icon_{size}x{size}.png"))
            # The @2x variants are what Retina actually draws.
            if size >= 32:
                img.save(os.path.join(iconset, f"icon_{size // 2}x{size // 2}@2x.png"))
        subprocess.run(
            ["iconutil", "-c", "icns", iconset, "-o", os.path.join(tmp, "AppIcon.icns")],
            check=True,
        )
        shutil.copy(os.path.join(tmp, "AppIcon.icns"), path)


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    master = render()

    if len(sys.argv) > 1:
        master.save(sys.argv[1])
        sys.exit(0)

    write_png(master, os.path.join(root, "assets", "icon-512.png"))
    print("wrote assets/icon-512.png", file=sys.stderr)
    write_icns(master, os.path.join(root, "assets", "AppIcon.icns"))
    print("wrote assets/AppIcon.icns", file=sys.stderr)
