#!/usr/bin/env python3
"""Builds the app icon from the chest render in `assets/chest-source.png`.

    python3 scripts/make-icon.py

Writes `assets/AppIcon.icns` for the macOS bundle and `src/icon_data.rs` for
the window icon, which is embedded rather than loaded from the bundle: the icon
cache once held on to a placeholder after a bad build, and a binary that
carries its own icon cannot be caught out that way.

The source render was generated by the author and sits on a cream backdrop.
It is cut out here — by `cutout.py`, which the door artwork shares — and then
used **zweimal, verschieden**:

* **Im Fenster** steht die Truhe frei, auf nichts ([`free_mark`]). Dort ist sie
  ein Gegenstand im Raum des Programms, und eine Platte darunter wäre ein
  Kasten um einen Kasten.
* **Als App-Icon** sitzt sie auf einer dunklen Holzplatte, die das ganze
  Quadrat füllt ([`plate_mark`]).

Das war einmal anders, und der Grund für die Änderung steht im Betriebssystem:
**macOS 26 zwingt jedes App-Icon in ein abgerundetes Quadrat.** Was dabei
durchsichtig ist, füllt es selbst — mit Weiß. Ein freistehender Gegenstand kam
so als kleine Truhe auf einer großen weißen Karte heraus, mit Rändern, die
niemand gewählt hat. Ältere macOS-Versionen zeigten Icons in jeder Form, und
dafür war der freie Stand die schönere Wahl; seit 26 ist er schlicht nicht mehr
möglich. Wer die Platte selbst mitbringt, bestimmt, was in dem Quadrat steht.

Die Rundung backt das Skript **nicht** ein: Das System schneidet sie ohnehin,
und zweimal gerundet gäbe einen hellen Saum an den Ecken.

Needs Pillow (`pip3 install pillow`). The generated files are committed, so
nobody has to run this to build the project.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFilter, ImageOps

from cutout import cutout, fit


N = 1024

GLOW = (255, 205, 132)

# Die zwei Enden der Holzplatte unter dem App-Icon: die Tiefen der Maserung und
# ihre Lichter. Dazwischen liegt dieselbe Nussbaum-Welt wie im Fenster.
DARK = (28, 20, 12)
MID = (74, 54, 34)

# Wohin die Vignette an den Rändern läuft — fast, aber nicht ganz Schwarz. Ganz
# schwarz stünde die Platte als Loch im Dock, wenn der Schreibtisch dunkel ist.
EDGE = (10, 7, 4)


def free_mark(cut):
    """The chest, standing on nothing.

    There used to be a tile behind it — a dark rounded square with a gradient,
    a border and a drop shadow — because that is the shape macOS expects of an
    icon. It was wrong in both places it appeared. Inside the window its
    gradient starts at (32, 36, 48) where the window paints (13, 15, 22), so it
    read as a lighter box around the chest with a visible seam. On the desktop
    it was a black slab behind an object that looks better without one.

    The warm glow stays. It is a soft radial that reads as light coming off the
    gold rather than as an edge, and it keeps the chest from looking pasted on.
    The drop shadow does not: an opaque ellipse with nothing to fall on is just
    a grey smudge.
    """
    out = Image.new("RGBA", (N, N), (0, 0, 0, 0))

    glow = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    for r, a in ((420, 14), (300, 20), (200, 26), (120, 34)):
        gd.ellipse([N // 2 - r, 470 - r * 0.7, N // 2 + r, 470 + r * 0.7], fill=GLOW + (a,))
    out = Image.alpha_composite(out, glow.filter(ImageFilter.GaussianBlur(60)))

    # With no plate to sit inside, the chest may use nearly the whole square.
    return Image.alpha_composite(out, fit(cut, N, 40))


def plate_mark(cut):
    """Die Truhe auf einer Holzplatte, die das ganze Quadrat füllt.

    Für das App-Icon, seit macOS 26 die Form vorgibt — siehe Kopf der Datei.

    Die Platte ist die Maserung des Programms, aber eingefärbt: Die Kachel in
    `assets/wood-256.png` ist fast farblos, weil das Fenster sie erst beim
    Zeichnen tönt. Hier übernimmt das [`ImageOps.colorize`] — Schwarz wird zu
    `DARK`, Weiß zu `MID`, und dazwischen liegt dasselbe Nussbaum wie im
    Fenster.

    Darüber eine Vignette: zu den Rändern hin fast schwarz. Sie hat zwei
    Aufgaben. Sie hebt die Truhe heraus, und sie hält die vier Ecken ruhig —
    genau dort schneidet die Maske des Systems, und eine Maserung, die
    mittendrin abgeschnitten wird, sieht nach Versehen aus.

    Die Truhe steht auf 74 Prozent der Kantenlänge. Voller ginge, aber die
    Rundung frisst die Ecken, und was an der Kante klebt, wirkt eingesperrt.
    """
    wood = Image.open(os.path.join(_assets(), "wood-256.png")).convert("L")
    plate = ImageOps.colorize(wood.resize((N, N), Image.LANCZOS), DARK, MID).convert("RGBA")

    vignette = Image.new("L", (N, N), 0)
    ImageDraw.Draw(vignette).ellipse(
        [-N * 0.15, -N * 0.15, N * 1.15, N * 1.15], fill=255
    )
    vignette = vignette.filter(ImageFilter.GaussianBlur(N * 0.12))
    plate = Image.composite(plate, Image.new("RGBA", (N, N), EDGE + (255,)), vignette)

    glow = Image.new("RGBA", (N, N), (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    for r, a in ((430, 16), (310, 22), (210, 30), (130, 40)):
        gd.ellipse([N // 2 - r, 520 - r * 0.7, N // 2 + r, 520 + r * 0.7], fill=GLOW + (a,))
    plate = Image.alpha_composite(plate, glow.filter(ImageFilter.GaussianBlur(70)))

    return Image.alpha_composite(plate, fit(cut, N, int(N * 0.13)))


def _assets():
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.join(os.path.dirname(here), "assets")


def render():
    return cutout(Image.open(os.path.join(_assets(), "chest-source.png")))


ICONSET_SIZES = [16, 32, 64, 128, 256, 512, 1024]

def write_png(master, path, n=512):
    """The window icon, as a PNG the binary carries and decodes at startup.

    It used to be a raw RGBA array in the source. At 128 pixels that array was
    already 2700 lines, and the intro screen draws the mark at 420 physical
    pixels on a Retina display, so it arrived visibly soft. Storing the same
    thing at 512 as an array would be a megabyte of Rust source; as a PNG it is
    a fraction of that and sharp.
    """
    master.resize((n, n), Image.LANCZOS).save(path)


def write_icns(master, path):
    import shutil
    import subprocess
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        iconset = os.path.join(tmp, "AppIcon.iconset")
        os.makedirs(iconset)
        for size in ICONSET_SIZES:
            img = master.resize((size, size), Image.LANCZOS)
            img.save(os.path.join(iconset, f"icon_{size}x{size}.png"))
            # The @2x variants are what Retina actually draws.
            if size >= 32:
                img.save(os.path.join(iconset, f"icon_{size // 2}x{size // 2}@2x.png"))
        subprocess.run(
            ["iconutil", "-c", "icns", iconset, "-o", os.path.join(tmp, "AppIcon.icns")],
            check=True,
        )
        shutil.copy(os.path.join(tmp, "AppIcon.icns"), path)


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    cut = render()
    window_mark = free_mark(cut)
    app_icon = plate_mark(cut)

    if len(sys.argv) > 1:
        app_icon.save(sys.argv[1])
        sys.exit(0)

    write_png(window_mark, os.path.join(root, "assets", "icon-512.png"))
    print("wrote assets/icon-512.png (freistehend, fürs Fenster)", file=sys.stderr)
    write_icns(app_icon, os.path.join(root, "assets", "AppIcon.icns"))
    print("wrote assets/AppIcon.icns (auf Platte, fürs Dock)", file=sys.stderr)
